const questions = {
  c: {
    easy:[
      {question:"C language developed by?",options:["Dennis Ritchie","James Gosling","Bjarne","Guido"],answer:0},
      {question:"C is which language?",options:["High level","Low level","Both","None"],answer:2},
      {question:"Extension of C file?",options:[".c",".cpp",".java",".py"],answer:0},
      {question:"C is?",options:["Compiled","Interpreted","Both","None"],answer:0},
      {question:"Main function returns?",options:["int","void","char","float"],answer:0},
      {question:"Keyword in C?",options:["int","hello","main1","None"],answer:0},
      {question:"Symbol for comment?",options:["//","##","@@","%%"],answer:0},
      {question:"Loop example?",options:["for","int","char","none"],answer:0},
      {question:"Array stores?",options:["Multiple values","One value","None","Text"],answer:0},
      {question:"Index starts from?",options:["0","1","-1","2"],answer:0},
      {question:"Header file?",options:["stdio.h","test.h","main.h","none"],answer:0},
      {question:"Printf used for?",options:["Output","Input","Loop","None"],answer:0},
      {question:"Scanf used for?",options:["Input","Output","Loop","None"],answer:0},
      {question:"Data type?",options:["int","loop","function","none"],answer:0},
      {question:"Character type?",options:["char","int","float","none"],answer:0},
      {question:"Float stores?",options:["Decimal","Integer","Text","None"],answer:0},
      {question:"Loop type?",options:["for","main","int","none"],answer:0},
      {question:"Function is?",options:["Block of code","Variable","Loop","None"],answer:0},
      {question:"Return keyword?",options:["return","stop","exit","none"],answer:0},
      {question:"Include keyword?",options:["#include","include","import","none"],answer:0},
      {question:"Define keyword?",options:["#define","define","int","none"],answer:0},
      {question:"Structure is?",options:["User defined","Loop","Function","None"],answer:0},
      {question:"Pointer is?",options:["Address","Value","Loop","None"],answer:0},
      {question:"Variable is?",options:["Storage","Loop","None","Function"],answer:0},
      {question:"Constant is?",options:["Fixed value","Loop","None","Var"],answer:0},
      {question:"Break used for?",options:["Exit loop","Enter loop","Print","None"],answer:0},
      {question:"Continue means?",options:["Skip iteration","Stop","Print","None"],answer:0},
      {question:"While loop?",options:["Condition loop","Print","None","Var"],answer:0},
      {question:"Do while?",options:["Exec once","Never","None","Loop"],answer:0}
    ],
    medium:[
      {question:"Which header file is used for printf?",options:["stdio.h","math.h","string.h","conio.h"],answer:0},
      {question:"Which operator is used to get address?",options:["&","*","#","@"],answer:0},
      {question:"Which loop checks condition first?",options:["for","do-while","none","switch"],answer:0},
      {question:"Array index starts from?",options:["0","1","-1","2"],answer:0},
      {question:"Which is entry controlled loop?",options:["for","do-while","none","switch"],answer:0},
      {question:"Which is exit controlled loop?",options:["do-while","for","while","none"],answer:0},
      {question:"Size of char?",options:["1 byte","2 byte","4 byte","8 byte"],answer:0},
      {question:"Size of int?",options:["2 byte","4 byte","8 byte","1 byte"],answer:1},
      {question:"Function returning void?",options:["void func()","int func()","float func()","none"],answer:0},
      {question:"Break statement used in?",options:["Loop","Switch","Both","None"],answer:2},
      {question:"Continue used in?",options:["Loop","Switch","Both","None"],answer:0},
      {question:"Default in switch?",options:["Else","Switch","None","Var"],answer:1},
      {question:"Pointer stores?",options:["Address","Value","Loop","None"],answer:0},
      {question:"Size of pointer?",options:["Depends on system","4 byte","8 byte","16 byte"],answer:0},
      {question:"sizeof operator returns?",options:["Size in bytes","Value","Address","None"],answer:0},
      {question:"Enum default type?",options:["int","char","float","none"],answer:0},
      {question:"Typedef is used for?",options:["Alias name","Loop","Var","None"],answer:0},
      {question:"Preprocessor directive?",options:["#include","#define","Both","None"],answer:2},
      {question:"Storage class auto?",options:["Local default","Global default","Static default","None"],answer:0},
      {question:"Register storage?",options:["CPU register","Memory","Disk","None"],answer:0},
      {question:"Extern keyword?",options:["Global access","Local access","None","Loop"],answer:0},
      {question:"Static variable?",options:["Retains value","Does not retain","None","Loop"],answer:0},
      {question:"Volatile keyword?",options:["Prevents optimization","Does not prevent","None","Loop"],answer:0},
      {question:"Function pointer?",options:["Callback","None","Loop","Var"],answer:0},
      {question:"Const keyword?",options:["Cannot modify","Can modify","None","Loop"],answer:0},
      {question:"Inline function?",options:["Request compiler inline","Normal function","None","Loop"],answer:0},
      {question:"Macro usage?",options:["Text replacement","Function","Both","None"],answer:0},
      {question:"Conditional operator?",options:["?:","&&","||","none"],answer:0},
      {question:"Comma operator?",options:["Sequence","Conditional","Both","None"],answer:0}
    ],
    hard:[
      {question:"Pointer to pointer called?",options:["Double Pointer","Array","Loop","Structure"],answer:0},
      {question:"Function pointer is used for?",options:["Callback","Loop","Array","None"],answer:0},
      {question:"Memory leak occurs when?",options:["Memory not freed","Memory freed","Loop","Var"],answer:0},
      {question:"Segmentation fault occurs?",options:["Invalid memory access","Normal","None","Loop"],answer:0},
      {question:"Dangling pointer?",options:["Points freed memory","Valid pointer","None","Loop"],answer:0},
      {question:"Heap memory?",options:["Dynamic allocation","Static allocation","None","Loop"],answer:0},
      {question:"Stack memory?",options:["Function call","Dynamic allocation","None","Loop"],answer:0},
      {question:"Recursion is?",options:["Function calls itself","Loop","Var","None"],answer:0},
      {question:"Static function?",options:["Local to file","Global","None","Loop"],answer:0},
      {question:"Volatile prevents?",options:["Optimization","Execution","Loop","Var"],answer:0},
      {question:"Const pointer?",options:["Cannot change pointer","Can change pointer","None","Loop"],answer:0},
      {question:"Void pointer?",options:["Generic pointer","Specific pointer","None","Loop"],answer:0},
      {question:"Inline function?",options:["Compiler inline request","Normal","None","Loop"],answer:0},
      {question:"Preprocessor macros?",options:["Text replacement","Function","Both","None"],answer:0},
      {question:"Bitwise AND operator?",options:["&","|","^","~"],answer:0},
      {question:"Bitwise OR operator?",options:["|","&","^","~"],answer:0},
      {question:"Bitwise XOR operator?",options:["^","&","|","~"],answer:0},
      {question:"Left shift operator?",options:["<<",">>","&","|"],answer:0},
      {question:"Right shift operator?",options:[">>", "<<","&","|"],answer:0},
      {question:"Signed int range?",options:["-32768 to 32767","0 to 65535","-128 to 127","-2147483648 to 2147483647"],answer:3},
      {question:"Unsigned int range?",options:["0 to 65535","-32768 to 32767","-128 to 127","0 to 4294967295"],answer:3},
      {question:"Function prototype?",options:["Declaration","Definition","Both","None"],answer:0},
      {question:"Storage class extern?",options:["Global","Local","Both","None"],answer:0},
      {question:"Const qualifier?",options:["Read only","Read/write","None","Loop"],answer:0},
      {question:"Register variable?",options:["Stored in CPU","Memory","Both","None"],answer:0},
      {question:"Static global variable?",options:["Retains value","Does not retain","None","Loop"],answer:0}
    ]
  },




dbms: {
  easy:[
    {question:"DBMS full form?",options:["Database Management System","Data Base Manual System","Data Binary Management System","None"],answer:0},
    {question:"Which is a type of DBMS?",options:["Hierarchical","Relational","Network","All of these"],answer:3},
    {question:"SQL stands for?",options:["Structured Query Language","Simple Query Language","Sequential Query Language","None"],answer:0},
    {question:"Primary key is?",options:["Unique identifier","Non unique","Optional","None"],answer:0},
    {question:"Foreign key?",options:["References primary key","Unique key","Null key","None"],answer:0},
    {question:"Which is DML?",options:["SELECT, INSERT, UPDATE","CREATE, DROP","GRANT, REVOKE","None"],answer:0},
    {question:"Which is DDL?",options:["CREATE, ALTER, DROP","SELECT, UPDATE","INSERT, DELETE","None"],answer:0},
    {question:"Tuple in DB?",options:["Row","Column","Table","Database"],answer:0},
    {question:"Attribute?",options:["Column","Row","Table","Database"],answer:0},
    {question:"Relation in DB?",options:["Table","Row","Column","Database"],answer:0},
    {question:"Normalization?",options:["Remove redundancy","Add redundancy","Delete table","None"],answer:0},
    {question:"1NF means?",options:["First Normal Form","Second Normal Form","Third Normal Form","None"],answer:0},
    {question:"2NF means?",options:["Second Normal Form","First Normal Form","Third Normal Form","None"],answer:0},
    {question:"3NF means?",options:["Third Normal Form","First Normal Form","Second Normal Form","None"],answer:0},
    {question:"Join used for?",options:["Combine tables","Separate tables","Delete table","None"],answer:0},
    {question:"Inner join?",options:["Matching rows","All rows","Non matching rows","None"],answer:0},
    {question:"Outer join?",options:["All rows with match","Matching only","None","Var"],answer:0},
    {question:"Candidate key?",options:["Unique key","Primary key","Foreign key","None"],answer:0},
    {question:"Super key?",options:["Candidate + extra","Primary key","Foreign key","None"],answer:0},
    {question:"Index in DB?",options:["Faster search","Slower search","None","Var"],answer:0},
    {question:"ACID properties?",options:["Atomicity, Consistency, Isolation, Durability","Atomic, Complete, Integrity, Data","None","Var"],answer:0},
    {question:"DBMS software?",options:["Oracle, MySQL, SQL Server, PostgreSQL","Python, C, Java","None","Var"],answer:0},
    {question:"Transaction?",options:["Sequence of DB operations","Single query","None","Var"],answer:0},
    {question:"Rollback?",options:["Undo transaction","Redo transaction","None","Var"],answer:0},
    {question:"Commit?",options:["Save transaction","Undo","None","Var"],answer:0},
    {question:"View in DB?",options:["Virtual table","Physical table","None","Var"],answer:0},
    {question:"Trigger?",options:["Auto action on event","Manual action","None","Var"],answer:0},
    {question:"Stored procedure?",options:["Precompiled SQL code","Normal SQL","None","Var"],answer:0},
    {question:"Cursor?",options:["Row pointer in result","Table pointer","None","Var"],answer:0},
    {question:"Deadlock?",options:["Two transactions wait each other","Transaction success","None","Var"],answer:0}
  ],
  medium:[
    {question:"ER model developed by?",options:["Peter Chen","E. F. Codd","James Gosling","Dennis Ritchie"],answer:0},
    {question:"Which is not a normal form?",options:["4NF","1NF","2NF","5thNF"],answer:3},
    {question:"DBMS layered architecture?",options:["Three-tier","Two-tier","Four-tier","One-tier"],answer:0},
    {question:"Relational algebra uses?",options:["Set theory","Loops","Array","None"],answer:0},
    {question:"SELECT * FROM table;",options:["Select all rows/columns","Select first row","Select columns only","None"],answer:0},
    {question:"JOIN type to include all rows?",options:["Outer join","Inner join","Cross join","None"],answer:0},
    {question:"PRIMARY KEY constraint?",options:["Unique and not null","Null allowed","Duplicate allowed","None"],answer:0},
    {question:"Foreign key can be null?",options:["Yes","No","Depends","None"],answer:0},
    {question:"Clustered index?",options:["Sorted physical order","Random","None","Var"],answer:0},
    {question:"Non-clustered index?",options:["Pointer to data","Direct data","None","Var"],answer:0},
    {question:"DBMS component for storage?",options:["Storage manager","Query processor","None","Var"],answer:0},
    {question:"DBMS component for query parsing?",options:["Query processor","Storage manager","None","Var"],answer:0},
    {question:"Tuple vs attribute?",options:["Row vs Column","Column vs Row","Table vs Column","None"],answer:0},
    {question:"Data dictionary stores?",options:["Metadata","Data","Transaction","None"],answer:0},
    {question:"Rollback segment?",options:["Undo information","Redo info","Data","None"],answer:0},
    {question:"Isolation level?",options:["Transaction visibility","User access","None","Var"],answer:0},
    {question:"Deadlock prevention?",options:["Wait-die, wound-wait","Random","None","Var"],answer:0},
    {question:"Two-phase commit?",options:["Distributed transaction commit","Single DB commit","None","Var"],answer:0},
    {question:"Check constraint?",options:["Restrict column value","Allow any value","None","Var"],answer:0},
    {question:"Default constraint?",options:["Default value","Mandatory value","None","Var"],answer:0},
    {question:"Unique constraint?",options:["No duplicate","Duplicate allowed","None","Var"],answer:0},
    {question:"Data type VARCHAR?",options:["Variable length string","Fixed length string","None","Var"],answer:0},
    {question:"Data type CHAR?",options:["Fixed length string","Variable length","None","Var"],answer:0},
    {question:"Data type INT?",options:["Integer","String","None","Var"],answer:0},
    {question:"Data type FLOAT?",options:["Decimal","Integer","None","Var"],answer:0},
    {question:"Composite key?",options:["Combination of columns","Single column","None","Var"],answer:0},
    {question:"Derived attribute?",options:["Computed from other","Directly stored","None","Var"],answer:0},
    {question:"Weak entity?",options:["Depends on strong entity","Independent","None","Var"],answer:0},
    {question:"Strong entity?",options:["Independent","Dependent","None","Var"],answer:0}
  ],
  hard:[
    {question:"Normalization goal?",options:["Eliminate redundancy","Increase redundancy","None","Var"],answer:0},
    {question:"3NF ensures?",options:["No transitive dependency","Redundancy allowed","None","Var"],answer:0},
    {question:"4NF ensures?",options:["No multi-valued dependency","Some dependency allowed","None","Var"],answer:0},
    {question:"5NF ensures?",options:["Decompose to join dependencies","Redundancy allowed","None","Var"],answer:0},
    {question:"BCNF ensures?",options:["Strict 3NF","Weak 3NF","None","Var"],answer:0},
    {question:"Relational model based on?",options:["Set theory","Array","Loop","None"],answer:0},
    {question:"Transaction atomicity?",options:["All or none","Partial allowed","None","Var"],answer:0},
    {question:"Transaction durability?",options:["Changes permanent","Undo allowed","None","Var"],answer:0},
    {question:"Transaction consistency?",options:["DB remains consistent","May corrupt","None","Var"],answer:0},
    {question:"Transaction isolation?",options:["Independent","Dependent","None","Var"],answer:0},
    {question:"Deadlock detection?",options:["Wait-for graph","Ignore","None","Var"],answer:0},
    {question:"Distributed DBMS?",options:["Multiple sites","Single site","None","Var"],answer:0},
    {question:"Replication?",options:["Copy DB to multiple sites","Single copy","None","Var"],answer:0},
    {question:"Sharding?",options:["Partition DB horizontally","Vertically","None","Var"],answer:0},
    {question:"ACID property A?",options:["Atomicity","Consistency","None","Var"],answer:0},
    {question:"ACID property C?",options:["Consistency","Atomicity","None","Var"],answer:0},
    {question:"ACID property I?",options:["Isolation","Durability","None","Var"],answer:0},
    {question:"ACID property D?",options:["Durability","Isolation","None","Var"],answer:0},
    {question:"CAP theorem C?",options:["Consistency","Availability","Partition tolerance","None"],answer:0},
    {question:"CAP theorem A?",options:["Availability","Consistency","Partition tolerance","None"],answer:0},
    {question:"CAP theorem P?",options:["Partition tolerance","Availability","Consistency","None"],answer:0},
    {question:"Index-organized table?",options:["Data stored with index","Data stored separate","None","Var"],answer:0},
    {question:"Materialized view?",options:["Stored query result","Temporary result","None","Var"],answer:0},
    {question:"Stored procedure optimization?",options:["Precompiled","Normal compile","None","Var"],answer:0},
    {question:"Trigger firing?",options:["Event driven","Manual","None","Var"],answer:0},
    {question:"Deadlock recovery?",options:["Rollback one transaction","Ignore","None","Var"],answer:0}
  ]
},

os: {
  easy:[
    {question:"OS full form?",options:["Operating System","Open Source","Output System","Optional System"],answer:0},
    {question:"Which is a type of OS?",options:["Batch","Time Sharing","Distributed","All of these"],answer:3},
    {question:"Kernel is?",options:["Core of OS","Peripheral","Application","None"],answer:0},
    {question:"Process?",options:["Program in execution","File","Thread","Variable"],answer:0},
    {question:"Thread?",options:["Lightweight process","Heavy process","Program","None"],answer:0},
    {question:"Multitasking?",options:["Multiple processes","Single process","None","Var"],answer:0},
    {question:"Scheduler?",options:["Decides process execution","Stores data","None","Var"],answer:0},
    {question:"Deadlock?",options:["Processes wait indefinitely","Processes terminate","None","Var"],answer:0},
    {question:"Context switch?",options:["Save & load process state","Switch users","None","Var"],answer:0},
    {question:"Interrupt?",options:["Signal to CPU","Signal to memory","None","Var"],answer:0},
    {question:"Virtual memory?",options:["Uses disk as RAM","Uses extra RAM","None","Var"],answer:0},
    {question:"Paging?",options:["Divide memory into fixed blocks","Divide processes","None","Var"],answer:0},
    {question:"Segmentation?",options:["Memory into variable blocks","Memory into fixed blocks","None","Var"],answer:0},
    {question:"Cache memory?",options:["Faster storage","Slower storage","None","Var"],answer:0},
    {question:"Spooling?",options:["Queue for printer","Store data","None","Var"],answer:0},
    {question:"Booting?",options:["Start OS","Shutdown","None","Var"],answer:0},
    {question:"Interrupt vector?",options:["Address of ISR","Data","None","Var"],answer:0},
    {question:"DMA stands for?",options:["Direct Memory Access","Data Memory Allocation","None","Var"],answer:0},
    {question:"Real time OS?",options:["Immediate response","Delayed","None","Var"],answer:0},
    {question:"Time sharing OS?",options:["Shares CPU time","Exclusive CPU","None","Var"],answer:0},
    {question:"Multiprocessor OS?",options:["Multiple CPUs","Single CPU","None","Var"],answer:0},
    {question:"Process state?",options:["New, Ready, Running, Waiting, Terminated","Only Running","None","Var"],answer:0},
    {question:"Semaphore?",options:["Synchronization tool","Data storage","None","Var"],answer:0},
    {question:"Race condition?",options:["Multiple access conflict","Single access","None","Var"],answer:0},
    {question:"Starvation?",options:["Process never gets CPU","Process gets CPU","None","Var"],answer:0},
    {question:"File system?",options:["Organize data","Process management","None","Var"],answer:0},
    {question:"Paging fault?",options:["Page not in memory","Page corrupted","None","Var"],answer:0},
    {question:"Thrashing?",options:["Excessive paging","Process waiting","None","Var"],answer:0},
    {question:"Boot loader?",options:["Load OS","Shutdown","None","Var"],answer:0},
    {question:"Kernel mode?",options:["Full access","Limited access","None","Var"],answer:0}
  ],
    medium:[
     {question:"Which OS type for multiple users?",options:["Multiuser","Single user","Batch","None"],answer:0},
    {question:"Preemptive scheduling?",options:["Can interrupt","Cannot interrupt","None","Var"],answer:0},
    {question:"Round Robin uses?",options:["Time quantum","Priority","None","Var"],answer:0},
    {question:"Priority scheduling?",options:["CPU based on priority","Equal share","None","Var"],answer:0},
    {question:"FCFS scheduling?",options:["First come first served","Last come first served","None","Var"],answer:0},
    {question:"Deadlock avoidance?",options:["Resource allocation graph","Ignore","None","Var"],answer:0},
    {question:"Banker's algorithm?",options:["Avoid deadlock","Detect deadlock","None","Var"],answer:0},
    {question:"Segmentation fault occurs?",options:["Invalid memory access","Valid memory","None","Var"],answer:0},
    {question:"Page replacement?",options:["Replace pages in memory","Replace registers","None","Var"],answer:0},
    {question:"LRU replacement?",options:["Least recently used","Most recently used","None","Var"],answer:0},
    {question:"FIFO replacement?",options:["First in first out","Last in first out","None","Var"],answer:0},
    {question:"Process control block stores?",options:["Process info","File info","None","Var"],answer:0},
    {question:"Inter-process communication?",options:["Message passing","Shared memory","None","Var"],answer:0},
    {question:"Mutex?",options:["Mutual exclusion","Memory lock","None","Var"],answer:0},
    {question:"Semaphore types?",options:["Binary, Counting","Single","None","Var"],answer:0},
    {question:"Zombie process?",options:["Terminated but in PCB","Running process","None","Var"],answer:0},
    {question:"Orphan process?",options:["Parent terminated","Child terminated","None","Var"],answer:0},
    {question:"File descriptor?",options:["Identifier for file","Memory address","None","Var"],answer:0},
    {question:"Pipe?",options:["Communication channel","Storage","None","Var"],answer:0},
    {question:"Socket?",options:["Network endpoint","Process","None","Var"],answer:0},
    {question:"Paging vs segmentation?",options:["Fixed vs variable","Both fixed","None","Var"],answer:0},
    {question:"Thrashing effect?",options:["Low CPU utilization","High CPU utilization","None","Var"],answer:0},
    {question:"Context switch overhead?",options:["CPU time","Memory","None","Var"],answer:0},
    {question:"Virtualization?",options:["Run multiple OS","Single OS","None","Var"],answer:0},
    {question:"Hypervisor?",options:["Virtual machine manager","CPU scheduler","None","Var"],answer:0},
    {question:"Monolithic kernel?",options:["Single large kernel","Modular kernel","None","Var"],answer:0},
    {question:"Microkernel?",options:["Minimal kernel","Large kernel","None","Var"],answer:0},
    {question:"Device driver?",options:["Interface with hardware","Software only","None","Var"],answer:0},
    {question:"System call?",options:["Request service from OS","Access memory directly","None","Var"],answer:0}
  ],
  hard:[
    {question:"Real-time OS task deadline?",options:["Must meet","Can miss","None","Var"],answer:0},
    {question:"Hard real-time?",options:["Strict deadline","Flexible deadline","None","Var"],answer:0},
    {question:"Soft real-time?",options:["Best effort deadline","Strict deadline","None","Var"],answer:0},
    {question:"Multilevel queue?",options:["Different priority queues","Single queue","None","Var"],answer:0},
    {question:"Multilevel feedback?",options:["Adjusts priority dynamically","Static priority","None","Var"],answer:0},
    {question:"Deadlock detection algorithm?",options:["Wait-for graph","Banker's","None","Var"],answer:0},
    {question:"Paging vs segmentation overhead?",options:["Paging less overhead","Segmentation more","None","Var"],answer:0},
    {question:"Demand paging?",options:["Load pages on demand","Load all pages","None","Var"],answer:0},
    {question:"Thrashing solution?",options:["Increase RAM","Decrease CPU","None","Var"],answer:0},
    {question:"CPU-bound process?",options:["Needs CPU intensive","IO intensive","None","Var"],answer:0},
    {question:"IO-bound process?",options:["Needs IO intensive","CPU intensive","None","Var"],answer:0},
    {question:"Starvation solution?",options:["Aging","Random","None","Var"],answer:0},
    {question:"Mutex deadlock prevention?",options:["Lock ordering","Random","None","Var"],answer:0},
    {question:"Semaphore deadlock prevention?",options:["Binary semaphore","Counting semaphore","None","Var"],answer:0},
    {question:"Virtual memory management?",options:["Paging & segmentation","Stack only","None","Var"],answer:0},
    {question:"Kernel mode vs User mode?",options:["Full vs limited","Both full","None","Var"],answer:0},
    {question:"Real-time scheduling?",options:["Rate-monotonic","FCFS","None","Var"],answer:0},
    {question:"Round-robin time slice?",options:["Fixed quantum","Variable quantum","None","Var"],answer:0},
    {question:"System call interface?",options:["API for programs","Direct memory","None","Var"],answer:0},
    {question:"Boot process sequence?",options:["BIOS -> Loader -> Kernel","Kernel -> Loader -> BIOS","None","Var"],answer:0},
    {question:"Interrupt handling steps?",options:["Save context -> ISR -> Restore","ISR -> Save -> Restore","None","Var"],answer:0},
    {question:"Device scheduling algorithm?",options:["FCFS, SSTF, SCAN","Random","None","Var"],answer:0},
    {question:"Page fault handling?",options:["OS loads required page","OS ignores","None","Var"],answer:0},
    {question:"Swap space usage?",options:["Temporary memory extension","Permanent storage","None","Var"],answer:0},
    {question:"Paging vs segmentation pros?",options:["Depends on requirement","Always paging better","None","Var"],answer:0},
    {question:"Kernel vs user services?",options:["Privileged vs unprivileged","Both same","None","Var"],answer:0},
    {question:"System performance metrics?",options:["CPU utilization, throughput, response time","Only CPU","None","Var"],answer:0},
    {question:"Multiprocessor scheduling?",options:["Parallel execution","Sequential","None","Var"],answer:0}
  ]
},
se: {
  easy:[
    {question:"SDLC full form?",options:["Software Development Life Cycle","System Data Logic Code","Software Data Logic Control","System Development Code"],answer:0},
    {question:"Requirement gathering purpose?",options:["Understand user needs","Write code","Test software","None"],answer:0},
    {question:"Feasibility study checks?",options:["Economic, Technical, Operational","Coding, Testing, Deployment","Design only","None"],answer:0},
    {question:"Software design includes?",options:["Architecture & modules","Testing only","Coding only","None"],answer:0},
    {question:"Waterfall model is?",options:["Linear sequential","Iterative","Agile","None"],answer:0},
    {question:"V-model is?",options:["Verification & Validation","Coding model","Testing model only","None"],answer:0},
    {question:"Agile model?",options:["Iterative, Incremental","Linear","None","Var"],answer:0},
    {question:"Scrum uses?",options:["Sprints","Waterfall","V-Model","None"],answer:0},
    {question:"Incremental model?",options:["Build in increments","All at once","None","Var"],answer:0},
    {question:"RAD stands for?",options:["Rapid Application Development","Random Access Design","None","Var"],answer:0},
    {question:"Prototyping model?",options:["Create prototype for feedback","Linear coding","None","Var"],answer:0},
    {question:"Software testing purpose?",options:["Find defects","Write code","Design only","None"],answer:0},
    {question:"Unit testing?",options:["Test individual module","Test whole system","None","Var"],answer:0},
    {question:"Integration testing?",options:["Test combined modules","Test one module","None","Var"],answer:0},
    {question:"System testing?",options:["Test complete system","Test module only","None","Var"],answer:0},
    {question:"Acceptance testing?",options:["Customer verifies system","Developer tests","None","Var"],answer:0},
    {question:"Maintenance type: Corrective?",options:["Fix defects","Add features","None","Var"],answer:0},
    {question:"Maintenance type: Adaptive?",options:["Change for environment","Fix defects","None","Var"],answer:0},
    {question:"Maintenance type: Perfective?",options:["Enhance performance","Fix defects","None","Var"],answer:0},
    {question:"Maintenance type: Preventive?",options:["Prevent future problems","Fix defects","None","Var"],answer:0},
    {question:"SRS document?",options:["Software Requirements Specification","System Resource Sheet","None","Var"],answer:0},
    {question:"Feasibility types?",options:["Technical, Economic, Operational","Linear, Iterative","None","Var"],answer:0},
    {question:"Design principles?",options:["Modularity, Cohesion, Coupling","Loops, Arrays","None","Var"],answer:0},
    {question:"Coding standards?",options:["Maintainable code","Random code","None","Var"],answer:0},
    {question:"Version control?",options:["Git, SVN","Excel","None","Var"],answer:0},
    {question:"Software metrics?",options:["Measure quality & productivity","Random numbers","None","Var"],answer:0},
    {question:"Risk management?",options:["Identify, Assess, Mitigate","Ignore","None","Var"],answer:0},
    {question:"Project scheduling?",options:["Timeline, Milestones","Random dates","None","Var"],answer:0},
    {question:"Effort estimation?",options:["COCOMO, Function points","Random","None","Var"],answer:0},
    {question:"Software quality?",options:["Meets requirements & standards","Random","None","Var"],answer:0}
  ],
  medium:[
    {question:"Spiral model?",options:["Risk-driven iterative","Linear sequential","None","Var"],answer:0},
    {question:"Prototyping advantage?",options:["Early feedback","Full product","None","Var"],answer:0},
    {question:"Agile value 1?",options:["Individuals & interactions","Processes & tools","None","Var"],answer:0},
    {question:"Agile value 2?",options:["Working software","Comprehensive docs","None","Var"],answer:0},
    {question:"Agile value 3?",options:["Customer collaboration","Contract negotiation","None","Var"],answer:0},
    {question:"Agile value 4?",options:["Responding to change","Following plan","None","Var"],answer:0},
    {question:"Coupling?",options:["Inter-module dependency","Module independence","None","Var"],answer:0},
    {question:"Cohesion?",options:["Single purpose module","Random","None","Var"],answer:0},
    {question:"White box testing?",options:["Internal code logic","External behavior","None","Var"],answer:0},
    {question:"Black box testing?",options:["External behavior","Internal code","None","Var"],answer:0},
    {question:"Alpha testing?",options:["Developers & testers","Customer only","None","Var"],answer:0},
    {question:"Beta testing?",options:["Customer testing","Developers","None","Var"],answer:0},
    {question:"Use case diagram?",options:["Actors & actions","Classes","None","Var"],answer:0},
    {question:"Class diagram?",options:["Classes & relations","Actors","None","Var"],answer:0},
    {question:"Sequence diagram?",options:["Order of interactions","Data storage","None","Var"],answer:0},
    {question:"Activity diagram?",options:["Workflow of activities","Actors","None","Var"],answer:0},
    {question:"Component diagram?",options:["System components & relations","Actors","None","Var"],answer:0},
    {question:"Deployment diagram?",options:["Physical deployment","Code logic","None","Var"],answer:0},
    {question:"ER diagram vs UML?",options:["Data vs Design","Both same","None","Var"],answer:0},
    {question:"Maintenance challenges?",options:["Changing requirements","Fixed product","None","Var"],answer:0},
    {question:"Project management?",options:["Plan, Schedule, Control","Random","None","Var"],answer:0},
    {question:"Configuration management?",options:["Version & change control","Random","None","Var"],answer:0},
    {question:"Software process model selection?",options:["Based on project type","Random","None","Var"],answer:0},
    {question:"Risk analysis?",options:["Identify & mitigate","Ignore","None","Var"],answer:0},
    {question:"Effort estimation metrics?",options:["LOC, Function points","Random","None","Var"],answer:0},
    {question:"Software cost estimation?",options:["COCOMO","Random","None","Var"],answer:0},
    {question:"SQA activities?",options:["Reviews, Testing, Audits","Random","None","Var"],answer:0},
    {question:"Software maintenance planning?",options:["Corrective, Adaptive, Perfective, Preventive","Random","None","Var"],answer:0},
    {question:"Software quality models?",options:["McCall, Boehm, ISO","Random","None","Var"],answer:0}
  ],
  hard:[
    {question:"Function points measure?",options:["Software size","Complexity","Random","None"],answer:0},
    {question:"COCOMO model?",options:["Effort estimation","Testing only","None","Var"],answer:0},
    {question:"Spiral risk phases?",options:["Identify, Analyze, Mitigate","Ignore","None","Var"],answer:0},
    {question:"Agile Scrum artifacts?",options:["Product backlog, Sprint backlog, Burn-down chart","Random","None","Var"],answer:0},
    {question:"Extreme programming (XP)?",options:["Rapid development & feedback","Linear development","None","Var"],answer:0},
    {question:"Pair programming benefit?",options:["Better code & review","Slower","None","Var"],answer:0},
    {question:"Continuous integration?",options:["Frequent code merge & test","Ignore","None","Var"],answer:0},
    {question:"Refactoring purpose?",options:["Improve design without changing behavior","Random","None","Var"],answer:0},
    {question:"Design pattern type?",options:["Creational, Structural, Behavioral","Random","None","Var"],answer:0},
    {question:"MVC pattern?",options:["Model, View, Controller","Random","None","Var"],answer:0},
    {question:"Singleton pattern?",options:["Single instance class","Multiple instance","None","Var"],answer:0},
    {question:"Factory pattern?",options:["Object creation abstraction","Random","None","Var"],answer:0},
    {question:"Observer pattern?",options:["Notify on state change","Random","None","Var"],answer:0},
    {question:"Adapter pattern?",options:["Convert interface","Random","None","Var"],answer:0},
    {question:"Decorator pattern?",options:["Add behavior dynamically","Random","None","Var"],answer:0},
    {question:"Strategy pattern?",options:["Algorithm encapsulation","Random","None","Var"],answer:0},
    {question:"State pattern?",options:["Object state change handling","Random","None","Var"],answer:0},
    {question:"Command pattern?",options:["Encapsulate requests","Random","None","Var"],answer:0},
    {question:"Mediator pattern?",options:["Central communication","Random","None","Var"],answer:0},
    {question:"Facade pattern?",options:["Simplify interface","Random","None","Var"],answer:0},
    {question:"Prototype pattern?",options:["Clone objects","Random","None","Var"],answer:0},
    {question:"Builder pattern?",options:["Step by step object creation","Random","None","Var"],answer:0},
    {question:"Bridge pattern?",options:["Decouple abstraction & implementation","Random","None","Var"],answer:0},
    {question:"Template method pattern?",options:["Define skeleton algorithm","Random","None","Var"],answer:0},
    {question:"Interpreter pattern?",options:["Interpret language grammar","Random","None","Var"],answer:0},
    {question:"Visitor pattern?",options:["Separate algorithm from object","Random","None","Var"],answer:0},
    {question:"Chain of responsibility?",options:["Pass request along chain","Random","None","Var"],answer:0}
  ]
}
}